---
- vars_prompt:
   - name: "Host"
     prompt: "Which Host"
     private: no
  hosts: "{{ Host }}"
  become: true
  become_user: root  
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/linux.yml
  tasks:
  - name: Turn on Masquerading
    shell:
      cmd: firewall-cmd --permanent --add-service=wireguard --zone=public
  - name: Reload firewall
    shell:
      cmd: firewall-cmd --reload
  - name: Enable IPv4 Frowarding
    file:
      path: /etc/sysctl.d/99-custom.conf
      state: touch
  - name: Configure Server
    blockinfile:
       path: /etc/sysctl.d/99-custom.conf
       block: |
          ## Turn on bbr ##
          net.core.default_qdisc = fq
          net.ipv4.tcp_congestion_control = bbr
 
          ## for IPv4 ##
          net.ipv4.ip_forward = 1
 
          ## Turn on basic protection/security ##
          net.ipv4.conf.default.rp_filter = 1
          net.ipv4.conf.all.rp_filter = 1
          net.ipv4.tcp_syncookies = 1
 
          ## for IPv6 - uncomment the following line ##
          #net.ipv6.conf.all.forwarding = 1
  - name: Reload Changes to systctl
    shell:
      cmd: sysctl -p /etc/sysctl.d/99-custom.conf
  - name: Allow Peer Connections 1
    shell:
      cmd: firewall-cmd --add-interface=wg0 --zone=internal
  - name: Allow Peer Connections 2
    shell:
      cmd: firewall-cmd --permanent --zone=internal --add-masquerade
    degug:
      msg: the firewall was changed on  {{ ansible_fqdn }}
