---
- vars_prompt:
   - name: "Host"
     prompt: "Which Host"
     private: no
   - name: "ip"
     prompt: "IP OF HOST"
     private: no
  hosts: "{{ Host }}"
  become: true
  become_user: root  
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/linux.yml
  tasks:
  roles:
    - centos8-update
    - add-epel-repo
    - add-elrepo-repo
    - centos8-update
    - install-kmod-wireguard
    - install-wireguard-tools
    - add-99-custom
  #- name: Turn on Masquerading
   # shell:
    #  cmd: firewall-cmd --permanent --zone=public --add-masquerade
