---
- vars_prompt:
    - name: "host"
      prompt: "Which Host"
      private: no
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/windows.yml
  tasks:
    - name: set startup type custom_service to delayed via powershell
      win_shell: 'Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\UsoSvc" | Select-Object -ExpandProperty DelayedAutoStart'
