---
- name: Removes superseded updates from WSUS server
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Cleanup WSUS
    win_shell: |
      [String]$WSUSserver = "WSUS"
      [Int32]$port =8530
      [Boolean]$SecureConnection = $False

      # .NET assembly WSUS inladen

      [void][reflection.assembly]::LoadWithPartialName("Microsoft.UpdateServices.Administration")

      # Variable used for counting the total number of declined updates
      $count = 0

      # Connecting to server

      $updateServer = [Microsoft.UpdateServices.Administration.AdminProxy]::getUpdateServer($WSUSserver,$SecureConnection,$port)

      write-host "Connected to WSUS Server" -foregroundcolor "green"

      $updatescope = New-Object Microsoft.UpdateServices.Administration.UpdateScope

      # Get the updates and check for superseded updates
      $u=$updateServer.GetUpdates($updatescope)

      foreach ($u1 in $u )
      {        
      if ($u1.IsSuperseded -eq 'True')
      # Declining superseded updates
      {
      write-host Declined Update : $u1.Title
      $u1.Decline()
      $count=$count + 1
      }
      }
      write-host Total Declined Updates: $count

      exit
    register: find_output

  - debug:
      msg: "{{ find_output.stdout.split('\n') }}"    