---
- name: Removes superseded updates from WSUS server
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  tasks:
  - name: Cleanup WSUS
    win_shell: C:\scripts\serverscripts\remove_superseded.ps1
    register: shell_result
      
  - name: Show Results
    debug:
      var: shell_result.stdout_lines
