---
- vars_prompt:
    - name: "host"
      prompt: "Which Host"
      private: no
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/windows.yml
  tasks:
  - name: Enable Remote Desktop
    win_shell: |
      function Disable-IEESC
      {
      $AdminKey = “HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}”
      Set-ItemProperty -Path $AdminKey -Name “IsInstalled” -Value 0
      $UserKey = “HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}”
      Set-ItemProperty -Path $UserKey -Name “IsInstalled” -Value 0
      Stop-Process -Name Explorer
      Write-Host “IE Enhanced Security Configuration (ESC) has been disabled.” -ForegroundColor Green
      }
      Disable-IEESC
