---
- vars_prompt:
    - name: "host"
      prompt: "Which Host"
      private: no
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/windows.yml
  tasks:
  - name: Check for missing updates
    win_updates:
      category_names:
        - Updates
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - DefinitionUpdates
        - WindowsDefender
        - Drivers
        - Tools
      state: searched
    register: kb
  - name: List missing updates
    debug:
      var: kb.updates
