---
- vars_prompt:
   - name: "Host"
     prompt: "Which Host"
     private: no
  hosts: "{{ Host }}"
  become: true
  become_user: root
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/linux.yml
  tasks:
   - name: Reboot
     reboot:
