- name: search for windows updates
  win_updates:
    category_names: "{{ patch_categories }}"
    state: searched
  register: win_updates_result
  when: guest.guestFamily == "windowsGuest"
- name: deploy report 
  template: 
    src: report.j2
    dest: /var/tmp/report.txt
  delegate_to: 127.0.0.1
  when: guest.guestFamily == "windowsGuest"
