---
# create a new VM from a template
- vars_prompt:
    - name: "vmname"
      prompt: "Name of VM"
      private: no
    - name: "memory_mb"
      prompt: "How Much Memory in MB"
      private: no
    - name: "size_gb"
      prompt: "Size of HD in GB"
      private: no
    - name: "ip"
      prompt: "IP"
      private: no
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/vmware.yml
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxi_hostname  }}"
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vmname }}"
        state: poweredon
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ size_gb }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: "{{ vlan }}"
          type: static
          ip: '{{ ip }}'
          netmask: '{{ netmask }}'
          gateway: '{{ gateway }}'
          dns_servers:
            - "{{ dns_server1 }}"
            - "{{ dns_server2 }}"
        hardware:
          memory_mb: "{{ memory_mb }}"
        wait_for_ip_address: True
        customization:
          domainadmin: "{{ domainadmin }}"
          domainadminpassword: "{{ domainadminpassword }}"
          joindomain: "{{ joindomain }}"
          timezone: "{{ timezone }}"
      delegate_to: localhost
