---
- vars_prompt:
    - name: "host"
      prompt: "Which Host"
      private: no
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - /etc/ansible/vault/vault.yml
    - /etc/ansible/group_vars/vmware.yml
  tasks:
  - name: Set Root Password No Expiration
    vmware_vm_shell:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      vm_id: "{{ vm_id }}"
      vm_username: "{{ vm_username }}"
      vm_password: "{{ vm_password }}"
      vm_shell: /bin/chage
      vm_shell_args: -M -l -E -l root
      validate_certs: False
    delegate_to: localhost
