---
- hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  connection: local
  tasks:
  - name: Add MOTD Banner
    ios_banner:
      banner: motd
      text: "{{ text_for_motd }}"
      state: present
    notify: "save ios"
  - name: Add Login Banner
    ios_banner:
      banner: login
      text: "{{ text_for_login }}"
      state: present
    notify: "save ios"
  handlers:
    - name: save ios
      ios_config:
        save_when: modified
